---
AllCops:
  Exclude:
    - 'Dangerfile'

# TODO: Remove this once this is migrated to resources
ChefModernize/Definitions:
  Exclude:
    - '**/definitions/*.rb'

# TODO: Remove this once this is migrated to resources
Lint/DuplicateMethods:
  Exclude:
    - 'libraries/base.rb'
    - 'libraries/command.rb'
    - 'libraries/contact.rb'
    - 'libraries/host.rb'
    - 'libraries/hostdependency.rb'
    - 'libraries/hostescalation.rb'
    - 'libraries/nagios.rb'
    - 'libraries/service.rb'
    - 'libraries/servicedependency.rb'
    - 'libraries/serviceescalation.rb'
    - 'libraries/timeperiod.rb'

# TODO: Remove this once this is migrated to resources
Lint/Void:
  Exclude:
    - 'libraries/command.rb'
